name: Dependency Submission
on:
  push:
    branches:
      - main

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.3
