name: SBOM Generation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # You can add multiple versions if you want to test compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

  #    - name: Run build
  #      run: npm run build

      # Optional: Run tests
      - name: Run tests
        run: npm test


      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn juiceshop -pv 1.0.0 -ps Philips_test -nsb https://sbom.philips.com -V Verbose
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          path: config
